# Generated by Django 6.0 on 2025-12-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Anomaly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(blank=True, max_length=50, null=True)),
                ("customer_id", models.CharField(blank=True, max_length=50, null=True)),
                ("product_id", models.CharField(blank=True, max_length=50, null=True)),
                ("anomaly_type", models.CharField(max_length=50)),
                ("details", models.JSONField()),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "anomalies",
            },
        ),
    ]
