# Generated by Django 6.0 on 2025-12-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anomalies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anomaly",
            name="anomaly_type",
            field=models.CharField(max_length=100),
        ),
    ]
